# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: Dev Environment
deployParameters:
  deploy-env: "development"
  deploy-project-id: "bcrbk9-dev"
  service-name: "strr-api-dev"
  container-name: "strr-api-dev"
  cloudsql-instances: "bcrbk9-dev:northamerica-northeast1:strr-db-dev"
  service-account: "sa-api@bcrbk9-dev.iam.gserviceaccount.com"
run:
 location: projects/bcrbk9-dev/locations/northamerica-northeast1
executionConfigs:
- usages: [DEPLOY, RENDER]
  artifactStorage: 'gs://c4hnrd-tools_clouddeploy/history'
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: test
description: Test Environment
deployParameters:
  deploy-env: "test"
  deploy-project-id: "bcrbk9-test"
  service-name: "strr-api-test"
  container-name: "strr-api-test"
  app-env: "test"
  cloudsql-instances: "bcrbk9-test:northamerica-northeast1:strr-db-test"
  service-account: "sa-api@bcrbk9-test.iam.gserviceaccount.com"
run:
 location: projects/bcrbk9-test/locations/northamerica-northeast1
executionConfigs:
- usages: [DEPLOY, RENDER]
  artifactStorage: 'gs://c4hnrd-tools_clouddeploy/history'
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: sandbox
description: Sandbox Environment
requireApproval: false
deployParameters:
  deploy-env: "sandbox"
  deploy-project-id: "bcrbk9-tools"
  service-name: "strr-api-sandbox"
  container-name: "strr-api-sandbox"
  app-env: "sandbox"
  cloudsql-instances: "bcrbk9-tools:northamerica-northeast1:strr-db-sandbox"
  service-account: "sa-api@bcrbk9-tools.iam.gserviceaccount.com"
run:
 location: projects/bcrbk9-tools/locations/northamerica-northeast1
executionConfigs:
- usages: [DEPLOY, RENDER]
  artifactStorage: 'gs://c4hnrd-tools_clouddeploy/history'
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: Production Environment
requireApproval: false
deployParameters:
  deploy-env: "production"
  deploy-project-id: "bcrbk9-prod"
  service-name: "strr-api-prod"
  container-name: "strr-api-prod"
  app-env: "production"
  cloudsql-instances: "bcrbk9-prod:northamerica-northeast1:strr-db-prod"
  service-account: "sa-api@bcrbk9-prod.iam.gserviceaccount.com"
  max-scale: "10"
  container-concurrency: "20"
run:
 location: projects/bcrbk9-prod/locations/northamerica-northeast1
executionConfigs:
- usages: [DEPLOY, RENDER]
  artifactStorage: 'gs://c4hnrd-tools_clouddeploy/history'